<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
xmlns:xi="http://w3.org/2001/XInclude">

<xsl:output method="html" version="1.0" indent="yes" encoding="utf-8" media-type="text/html" cdata-section-elements="LOGFILE" doctype-public="-//W3C//DTD XHTML 1.0 Strict//EN" doctype-system="http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"/>

<xsl:preserve-space elements="test" />
 
<xsl:template match="/">
 	<html>
 		<head>
			<title>GlobalTester: Professional Open Source for Chip Card Testing | GlobalTester</title>
		</head>
 	
 		<body style="font-family:Verdana; font-size:10pt; color:black">
		<div>
			<TABLE cellSpacing="0" cellPadding="0" border="0" frame="void">
	 			<TR><TD>
 					<img src="Header_GT.png"/>
 				</TD></TR>
			</TABLE>
 		</div>
		
 		<strong style="font-family:Verdana; font-size:14pt; color:black">GlobalTester Test Report
 		</strong>
 
 		<xsl:variable name="reportDir" select="TESTREPORT/REPORTDIR"/>
 
  		<xsl:apply-templates />

		<br />
		<h3> 4) Overview of executed test cases </h3>
		<p>  	
			
			<table border="1">
  				<tr>
    				<th bgcolor="#C0C0C0">Test Case ID</th>
    				<th bgcolor="#C0C0C0">Description</th>
    				<th bgcolor="#C0C0C0">Time (s)</th>
    				<th bgcolor="#C0C0C0">Result</th>
  				</tr>
  	 			<xsl:for-each select="TESTREPORT/TESTCASE">
 					<tr>
  					<td valign="top"><xsl:value-of select="TESTCASEID" /></td>
  					<td valign="top"><xsl:value-of select="TESTCASEDESCR" /></td>
  					<td valign="top"><xsl:value-of select="TESTCASETIME" /></td>
  					
  					<xsl:if test="TESTCASESTATUS='PASSED'">
  						<td valign="top" style="color:green">
  							<xsl:value-of select="TESTCASESTATUS"/>
  						</td>
  					</xsl:if>

  					<xsl:if test="TESTCASESTATUS='FAILURE'">
  						<td valign="top" style="color:red">
  							
  							<a><xsl:attribute name="href">
  							#<xsl:value-of select="TESTCASEFAILURE/FAILUREID"/>
 							</xsl:attribute><xsl:value-of select="TESTCASESTATUS" />
 							</a>
  						</td>
  					</xsl:if>
  					<xsl:if test="TESTCASESTATUS='WARNING'">
  						<td valign="top" style="color:red">
  							<a><xsl:attribute name="href">
  							#<xsl:value-of select="TESTCASEFAILURE/FAILUREID"/>
 							</xsl:attribute><xsl:value-of select="TESTCASESTATUS" />
 							</a>
  						</td>
  					</xsl:if>
 					<xsl:if test="TESTCASESTATUS='NOT APPLICABLE'">
  						<td valign="top" style="color:blue">
  							<a><xsl:attribute name="href">
  							</xsl:attribute><xsl:value-of select="TESTCASESTATUS" />
 							</a>
  						</td>
  					</xsl:if>
  					<xsl:if test="TESTCASESTATUS='UNDEFINED'">
  						<td valign="top" style="color:gray">
  							<a><xsl:attribute name="href">
  							</xsl:attribute><xsl:value-of select="TESTCASESTATUS" />
 							</a>
  						</td>
  					</xsl:if>

 					</tr>
 				</xsl:for-each>
  
			</table>
		</p>
 		 
 		 <br /> 
 		 <h3> 5) Test case results  </h3>
 		 <xsl:for-each select="TESTREPORT/TESTCASE">
			<a>
   				<xsl:attribute name="name">
    			<xsl:value-of select="TESTCASEFAILURE/FAILUREID"/>
   				</xsl:attribute>
  			</a>

 		  <h4>Test case ID: <xsl:value-of select="TESTCASEID"/></h4>
 		  
 		  <b>Description: </b> <xsl:value-of select="TESTCASEDESCR"/> <br />
 		  
		  <xsl:variable name="testcaseComment" select="TESTCASECOMMENT"/>
 		  <xsl:if test="string-length(TESTCASECOMMENT)>=1">
 		  	<b>Comment: </b><xsl:call-template name="COMMENTTEXT"/> <br /> 
 		  	<!--Comment: <xsl:value-of select="TESTCASECOMMENT"/> <br />-->
 		  </xsl:if>
 		  
 		  
 		  <xsl:variable name="numberOfFailures" select="count(./child::TESTCASEFAILURE)"/>
 		   		  		  
 		  <xsl:if test="$numberOfFailures = 0">
 		  	<b>Status: </b> Test case passed. <br />
 		  	For test results please refer the log file generated by GlobalTester in the specified logging folder.
 		  </xsl:if>

 		  <xsl:if test="$numberOfFailures > 0">
 		  	<b>Status: Test case failed! </b>
 		  </xsl:if>
 		  
 		  <xsl:for-each select="TESTCASEFAILURE">
			<p>
			<table>
			<colgroup>
    			<col width="120"></col>
    		</colgroup>
			<tr>
				<td> FailureID: </td>
				<td>
					<xsl:value-of select="FAILUREID"/>
				</td>
			</tr>
			<tr>
				<td>Description: </td>
				<td>
					<xsl:value-of select="DESCRIPTION"/>
				</td>
			</tr>
			<tr>
				<td>Expected value:</td>
				<td>
					<xsl:value-of select="EXPECTEDVALUE"/>
				</td>
			</tr>
			<tr>
				<td>Received value:</td>
				<td>
					<xsl:value-of select="RECEIVEDVALUE"/>
				</td>
			</tr>
			<tr>
				<td>Rating:</td>
				<td>
					<xsl:value-of select="RATING"/>
				</td>
			</tr>
			<tr>
				<td>Line in log file:</td>
				<td>
					<xsl:value-of select="LINELOGFILE"/>
				</td>
			</tr>
			<tr>
				<td>Comment:</td>
				<td>
					For full details please refer to the log file of GlobalTester.
				</td>
			</tr>
			</table>
			</p>
		  </xsl:for-each>
		  <hr />
		  </xsl:for-each>
  		
 		<!-- List summary of DG1 and DG2 if file is available-->

		<xsl:variable name="dg1file" select="document(concat($reportDir, '/dg1.xml'))"/>
 		
 		<xsl:if test="$dg1file/DG1/ISSUINGSTATE != ''">
 		
		<br />
		<h3>6) Summary of e-Passport information</h3>
			
		
		<table border="1">
			<tr>
				<td> Issuing state: </td>
				<td>
					<xsl:apply-templates 	select="$dg1file/DG1/ISSUINGSTATE" />
				</td>
			</tr>
			<tr>
				<td> Holder name: </td>
				<td>
					<xsl:apply-templates 	select="$dg1file/DG1/HOLDERNAME" />
				</td>
			</tr>
			<tr>
				<td> Document number: </td>
				<td>
					<xsl:apply-templates 	select="$dg1file/DG1/DOCNUMBER" />
				</td>
			</tr>
			<tr>
				<td> State: </td>
				<td>
					<xsl:apply-templates 	select="$dg1file/DG1/STATE" />
				</td>
			</tr>
			<tr>
				<td> Date of birth: </td>
				<td>
					<xsl:apply-templates 	select="$dg1file/DG1/DOB" />
				</td>
			</tr>
			<tr>
				<td> Sex: </td>
				<td>
					<xsl:apply-templates 	select="$dg1file/DG1/SEX" />
				</td>
			</tr>
			<tr>
				<td> Date of expiry:	</td>
				<td>
					<xsl:apply-templates 	select="$dg1file/DG1/DOE" />
				</td>
			</tr>
			<tr>
				<td> Optional data: </td>
				<td>
					<xsl:apply-templates 	select="$dg1file/DG1/OPTDATA" />
				</td>
			</tr>
			<tr>
				<td> MRZ1: </td>
				<td>
					<Code><xsl:apply-templates 	select="$dg1file/DG1/MRZ1" /></Code>
				</td>
			</tr>
			<tr>
				<td> MRZ2: </td>
				<td>
					<Code><xsl:apply-templates 	select="$dg1file/DG1/MRZ2" /></Code>
				</td>
			</tr>

			<tr>
				<td> Picture: </td>
				<td>
					<img src="dg2.jpg" alt="Image of passport owner"/>
				</td>
			</tr>
		</table>
		</xsl:if>
 	
 		<p>
 			<i>
 				Test Report generated by GlobalTester. For further information look at www.globaltester.org 			
 			</i>
 		</p>
 	
 	</body></html>
</xsl:template>

<xsl:template match="TESTREPORT">
   <h3> 1) Test summary </h3>

   <xsl:apply-templates select="SPECNAME" />
   <xsl:apply-templates select="SPECVERSION" />
   <xsl:apply-templates select="RELEASE" />
   <xsl:apply-templates select="RELEASEDATE" />
   <xsl:apply-templates select="TESTSUITEID" />
   <xsl:apply-templates select="SHORTDESCRIPTION" />
   <xsl:apply-templates select="STATUS" />
   
   <br /><h3>2) Test setup </h3>
   <xsl:apply-templates select="PLATFORMID" />
   <xsl:apply-templates select="SAMPLEID" />
   <xsl:apply-templates select="READER" />
   <xsl:apply-templates select="INTEGRITY" />
   <xsl:apply-templates select="PROFILES" />
   <xsl:apply-templates select="ADDITIONALINFO" />
   
		
   <br /><h3>3) Test statistics </h3>
   <xsl:apply-templates select="DATE" />
   <xsl:apply-templates select="USER" />
   <xsl:apply-templates select="TESTSESSIONTIME" />
   <xsl:apply-templates select="EXECUTEDTESTS" />
   <xsl:apply-templates select="PASSEDTESTS" />
   <xsl:apply-templates select="FAILEDTESTS" />   
   <xsl:apply-templates select="FAILURES" />
   <xsl:apply-templates select="WARNINGS" />
   <xsl:apply-templates select="LOGFILE" />
</xsl:template>


<xsl:template match="SPECNAME">
 <p style="font-family:Verdana; font-size:12pt; color:black">
   <strong>Specification: </strong>
   <xsl:apply-templates />
 </p>
</xsl:template>

<xsl:template match="SPECVERSION">
 <p style="font-family:Verdana; font-size:12pt; color:black">
   <strong>Specification Version: </strong>
   <xsl:apply-templates />
 </p>
</xsl:template>

<xsl:template match="RELEASE">
 <p style="font-family:Verdana; font-size:12pt; color:black">
   <strong>Release: </strong>
   <xsl:apply-templates />
 </p>
</xsl:template>

<xsl:template match="RELEASEDATE">
 <p style="font-family:Verdana; font-size:12pt; color:black">
   <strong>Release Date: </strong>
   <xsl:apply-templates />
 </p>
</xsl:template>


<xsl:template match="TESTSUITEID">
 <p style="font-family:Verdana; font-size:12pt; color:black">
   <strong>Test Suite ID: </strong>
   <xsl:apply-templates />
 </p>
</xsl:template>


<xsl:template match="SHORTDESCRIPTION">
 <p style="font-family:Verdana; font-size:12pt; color:black">
   <strong>Short Description: </strong>
   <xsl:apply-templates />
 </p>
</xsl:template>




<xsl:template match="STATUS">
 <p style="font-family:Verdana; font-size:12pt; color:black">
   <strong>Result: </strong> 
   <xsl:if test=".='PASSED'">
   		<span  style="background-color:#00FF00"><xsl:apply-templates /></span>
   </xsl:if>
   <xsl:if test=".='FAILURE'">
   		<span  style="background-color:#FF0000">FAILED</span>
   </xsl:if>
   <xsl:if test=".='WARNING'">
   		<span  style="background-color:#FFFF00">PASSED WITH WARNING(S)</span>
   </xsl:if>
 </p>
</xsl:template>


<xsl:template match="DATE">
 <p style="font-family:Verdana; font-size:12pt; color:black">
   <strong>Test executed at: </strong>
   <xsl:apply-templates />
 </p>
</xsl:template>

<xsl:template match="USER">
 <p style="font-family:Verdana; font-size:12pt; color:black">
   <strong>Test executed by: </strong>
   <xsl:apply-templates />
 </p>
</xsl:template>

<xsl:template match="PLATFORMID">
 <p style="font-family:Verdana; font-size:12pt; color:black">
   <strong>Platform ID: </strong>
   <xsl:apply-templates />
 </p>
</xsl:template>
	
<xsl:template match="SAMPLEID">
 <p style="font-family:Verdana; font-size:12pt; color:black">
   <strong>Sample ID: </strong>
   <xsl:apply-templates />
 </p>
</xsl:template>
	
<xsl:template match="READER">
 <p style="font-family:Verdana; font-size:12pt; color:black">
   <strong>Card Reader: </strong>
   <xsl:apply-templates />
 </p>
</xsl:template>

<xsl:template match="INTEGRITY">
 <p style="font-family:Verdana; font-size:12pt; color:black">
   <strong>Integrity of test suite: </strong>
   <xsl:apply-templates />
 </p>
</xsl:template>

<xsl:template match="PROFILES">
 <p style="font-family:Verdana; font-size:12pt; color:black">
   <strong>Profiles tested: </strong>
   <xsl:apply-templates />
 </p>
</xsl:template>

<xsl:template match="LOGFILE">
 <p style="font-family:Verdana; font-size:12pt; color:black">
   <strong>Corresponding logging file: </strong>
   <xsl:apply-templates />
 </p>
</xsl:template>

<xsl:template match="link">
  <a>
   <xsl:attribute name="href">
    <xsl:value-of select="@href" />
   </xsl:attribute>
   <xsl:apply-templates/>
  </a>
</xsl:template>
	
<xsl:template match="ADDITIONALINFO">
  <xsl:for-each select="INFOELEMENT">
	<p style="font-family:Verdana; font-size:12pt; color:black">
		<strong style="padding-right: 2mm"> <xsl:value-of select="INFOSOURCE" /> </strong>		
	  <xsl:value-of select="INFOTEXT" />
	</p>
  </xsl:for-each>
</xsl:template>

<xsl:template match="TESTSESSIONTIME">
 <p style="font-family:Verdana; font-size:12pt; color:black">
   <strong>Execution time: </strong> 
   <xsl:apply-templates /> s.
 </p>
</xsl:template>

<xsl:template match="EXECUTEDTESTS">
 <p style="font-family:Verdana; font-size:12pt; color:black">
   <strong>Number of tests executed: </strong> 
   <xsl:apply-templates />
 </p>
</xsl:template>

<xsl:template match="PASSEDTESTS">
 <p style="font-family:Verdana; font-size:12pt; color:black">
   <strong>Number of tests passed: </strong> 
   <xsl:apply-templates />
 </p>
</xsl:template>

<xsl:template match="FAILEDTESTS">
 <p style="font-family:Verdana; font-size:12pt; color:black">
   <strong>Number of tests failed: </strong> 
   <xsl:apply-templates />
 </p>
</xsl:template>


<xsl:template match="FAILURES">
 <p style="font-family:Verdana; font-size:12pt; color:black">
   <strong>Number of Failures: </strong> 
   <xsl:apply-templates />
 </p>
</xsl:template>

<xsl:template match="WARNINGS">
 <p style="font-family:Verdana; font-size:12pt; color:black">
   <strong>Number of Warnings: </strong> 
   <xsl:apply-templates />
 </p>
</xsl:template>

<xsl:template match="REFERENCES">
 <p style="font-family:Verdana; font-size:12pt; color:black">
   <strong>References: </strong> 
   <xsl:apply-templates />
 </p>
</xsl:template>
 

<xsl:template name="COMMENTTEXT">
 <xsl:param name="input" select="TESTCASECOMMENT"/>
 <xsl:choose>
   <xsl:when test="contains($input, '&#xA;')">
     <xsl:value-of select="substring-before($input, '&#xA;')"/>
     <br/>
     <xsl:call-template name="COMMENTTEXT">
       <xsl:with-param name="input" select="substring-after($input,'&#xA;')"/>
     </xsl:call-template>
   </xsl:when>
   <xsl:otherwise>
           <xsl:value-of select="$input"/>
   </xsl:otherwise>
 </xsl:choose>
</xsl:template>


</xsl:stylesheet>